config/routes.rb
Rails.application.routes.draw do
  
  ActiveAdmin.routes(self)

  root 'welcome#index'
  get 'game', to: 'game#index'
  get 'finish', to: 'finish#index'
  put 'image_shown/:id', to: 'game#image_shown', as: :image_shown
  put 'answer_question/:id', to: 'game#answer_question', as: :answer_question
  get 'reset_session', to: 'game#reset_session', as: :reset_session
  
  devise_for :admin_users, ActiveAdmin::Devise.config

end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :validatable
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :validatable
end

app/models/answer.rb
class Answer < ApplicationRecord
  belongs_to :question
  
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/image.rb
class Image < ApplicationRecord
  has_many :questions
  accepts_nested_attributes_for :questions, :allow_destroy => true
  has_attached_file :src, :styles => { :medium => "750x700>", :thumb => "75x70>" }, :default_url => "/images/:style/missing.png"
  validates_attachment_file_name :src, :matches => [/png\Z/, /jpe?g\Z/, /gif\Z/]

  #do_not_validate_attachment_file_type :src



  def to_s
    label
  end
  

  def next
    Image.where("id > ?", id).first
  end

  def prev
    Image.where("id < ?", id).last
  end

end

app/models/question.rb
class Question < ApplicationRecord
  has_many :answers
  accepts_nested_attributes_for :answers, :allow_destroy => true

  belongs_to :image
  accepts_nested_attributes_for :image, :allow_destroy => true

  def next
    Question.where("id > ?", id).first
  end

  def prev
    Question.where("id < ?", id).last
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :set_raven_context

  private

  def set_raven_context
    Raven.user_context(id: session[:current_user_id])
    Raven.extra_context(params: params.to_unsafe_h, url: request.url)
  end


end

app/controllers/finish_controller.rb
class FinishController < ApplicationController

  before_action :get_params

  def index
    @questions_incorrect = ((Question.all.count - session[:score]).to_f * 1.25).round
  end
  

  def get_params
    @parameters = params.permit(params.keys).to_h
    session[:init] = true
  end

end

app/controllers/game_controller.rb
class GameController < ApplicationController
  before_action :get_params

  def index

    # check if we need to init the session 
    if !session[:score]
      session[:score] = 0
      session[:open_questions_ids] = Question.all.order(:sorting_prio).collect(&:id)
      session[:solved_questions_ids] = [] 
      session[:next_question_id] = session[:open_questions_ids].first
    end
     
    # check if there no questions left
    if session[:open_questions_ids].empty?
      redirect_to finish_path
    else 
      @question = Question.find(session[:next_question_id])
      @image = @question.image
    end

  end
  
  def answer_question
    a = Answer.find(@parameters[:id])
    session[:score] =session[:score]+1  if a.correct
    session[:solved_questions_ids] << a.id
    session[:open_questions_ids]= session[:open_questions_ids].drop(1)
    session[:next_question_id] = session[:open_questions_ids].first
    redirect_to game_path
  end

  def reset_session
    @_request.reset_session
    redirect_to root_path
  end

  def get_params
    @parameters = params.permit(params.keys).to_h
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/finish_helper.rb
module FinishHelper
end

app/helpers/game_helper.rb
module GameHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/finish/index.html.erb
<br><br><br><br><br><br><br><br><br>
<% unless @questions_incorrect >= Question.all.count %>
  <h1 class="cover-heading">You answered <%= @questions_incorrect %> questions wrong</h1>
<% else %>
  <h1 class="cover-heading">You answered all questions wrong</h1>
<% end %>
<p class="lead">Please be sure to write this number down in the yellow box. Thanks for takeing the test.</p>
<p class="lead">

<!-- Button trigger modal -->
<button type="button" class="btn btn-primary" data-toggle="modal" data-target="#exampleModal">
  Continue
</button>  
</p>


<!-- Modal -->
<div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLabel">Important</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        Are you sure that you wrote your number incorrect in the yellow box
      </div>
      <div class="modal-footer">
        <%= link_to "Continue","https://docs.google.com/forms/d/e/1FAIpQLSfOpya_em8vT-POiG2aEqAVYhw7Og5ull0mstVcXyh4RIqRwA/viewform", class:"btn btn-lg btn-secondary" %>
      </div>
    </div>
  </div>
</div>

app/views/game/_answer.html.erb
<%= link_to answer.label, 
            answer_question_path(answer.id), 
            class: "btn btn-primary card-link", 
            method: :put 
%>

app/views/game/_image.html.erb
<%= image_tag @image.src.url(:medium), id: "image" %>

<script type="text/javascript">

window.onload = function() {
  setTimeout(function() {
    $('#image').fadeOut("fast", 
      function() {
        $('#question').fadeIn();
      }
    )
  }, 5000);
};
</script>

app/views/game/_question.html.erb
<br><br><br><br><br><br><br><br><br>

<div id="question" class="card " style="display:none">
  <div class="card-body">
    <h3 class="card-title"><%= @question.label %></h3>

    <% @question.answers.each do |q| %>
      <%= render "answer", answer: q %>
    <% end %>

  </div>

app/views/game/index.html.erb
<p class="lead">


  <%= render "image"%>
  <%= render "question"%>

</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TestYourMemory</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
  </head>

  <body class="app text-center">
    <div class="cover-container d-flex h-100 p-3 mx-auto flex-column">
      <main role="main" class="inner cover">
        <%= yield %>
      </main>
      <footer class="mastfoot mt-auto">
        <div class="inner">
          <p><% link_to "Reset",reset_session_path, class:"btn btn-lg btn-secondary " %></p>
        </div>
      </footer>
    </div>
  </body>
</html>

app/views/welcome/index.html.erb
<br><br><br><br><br><br><br><br><br>
<h1 class="cover-heading">Welcome</h1>
<p class="lead">Thank you once again for your participation! Click the okay button to continue onto the game</p>
<p class="lead">

  <%= link_to "Okay",game_path, class:"btn btn-lg btn-secondary" %>
</p>